name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@fused
        with:
          docs-folder: doc/
          conda-environment: doc/environment.yml
          formats: |-
            epub
            pdf
